# Generated by Django 4.1.7 on 2023-07-14 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('berries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('address', models.CharField(max_length=250)),
                ('comment', models.TextField(blank=True, max_length=5000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('berry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='berries.berries')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='berries.categories')),
            ],
        ),
    ]
