# Generated by Django 4.2.1 on 2023-07-02 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('berries', '0002_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='berries',
            name='currency',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='berries.currency'),
        ),
    ]
