# Generated by Django 4.1.7 on 2023-07-14 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berries', '0002_orders2'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders2',
            name='phone_number',
            field=models.CharField(blank=True, max_length=13),
        ),
    ]
